[package]
name = "advent-of-code-2025"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
http-cache-surf = "0.15.0"
indicatif = "0.18.3"
itertools = "0.14.0"
smol = "2.0.2"
surf = "2.3.2"
